### ISSUE TITLE
KeyError: '_MaxMode'

### ISSUE THREAD

**Issue by mabek** [mampfes/ha_bayernluefter#1]
Hi, 
receiving the following in  system log:

  File "/config/custom_components/bayernluefter/fan.py", line 88, in preset_mode
    if self._device.raw_converted()["_MaxMode"]:
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: '_MaxMode'

**Comment by mampfes** [comment]
Did you upload the template file to the device?
https://github.com/mampfes/ha_bayernluefter?tab=readme-ov-file#template-file

**Comment by mabek** [comment]
Hi, yes you are right, I did not! 
Now after doing so I get a different error:

2023-12-26 10:36:16.154 ERROR (MainThread) [custom_components.bayernluefter] Unexpected error fetching bayernluefter data: 'NoneType' object has no attribute 'named'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bayernluefter/__init__.py", line 96, in _async_update_data
    await self._device.update()
  File "/usr/local/lib/python3.11/site-packages/pyernluefter/__init__.py", line 74, in update
    parse_dict = parse.parse(self.template, state).named
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'named'

**Comment by mampfes** [comment]
Looks like you messed up the template file somehow. Did you download it as raw? What do you get if you open the following page in your browser?
http://192.168.0.73/index.html?export=1    --> replace 192.168.0.73 with the IP address of your Bayernluefter.
The template file should look like the previous one, just with some extra lines for e.g. MaxMode

**Comment by mabek** [comment]
Output looks fine for me:
# MUSTER FUER MASCHINENLESBAREN YAML-EXPORT

# Der Aufruf erfolgt durch:
# http://Ihre-IP-Adresse/index.html?export=1

# Das Format kann selbst angepasst werden, so dass die Parameter von einem Smarthome-System ausgelesen werden koennen.
# Sie finden die export.txt im Experten-Browser, nach dem Anklicken vom Zahnrad im Live-Schema

# Ein weiteres Template ist als XML verfuegbar
# Es kann hier heruntergeladen werden: www.bayernluft.de/de/download/export.txt

Date: 26.12.2023
Time: 13:25:41
DeviceName: 348518510364
MAC: 348518510364
LocalIP: 192.168.178.177
RSSI: -42
FW_MainController: Rev2.1
FW_WiFi: WS32235001
SystemMode: Kellermode
SystemOn: 1
Speed_In: 05
Speed_Out: 10
Speed_AntiFreeze: 00
Temp_In: 14,6
Temp_Out: 15,8
Temp_Fresh: 10,5
rel_Humidity_In: 52,2
rel_Humidity_Out: 74,4
abs_Humidity_In: 6,5
abs_Humidity_Out: 10,0
Efficiency: 77,5
Humidity_Transport: -1323
FrostschutzAktiv: 0
Frozen: 0
AbtauMode: 0
VermieterMode: 0
QuerlueftungAktiv: 0
MaxMode: 0

**Comment by mampfes** [comment]
You have to reload the integration after the template has been changed (or restart Home Assistant).

I will add this info to the README.

**Comment by mabek** [comment]
That worked, thanks a lot for your help!
