### ISSUE TITLE
Update to HACS 2.0 results in "[...]does not set FanEntityFeature.TURN_OFF but implements the turn_off method"

### ISSUE THREAD

**Issue by hlinden** [mampfes/ha_bayernluefter#10]
After fully updating HA and HACS today, I'm encountering this error in the logs:

```
Logger: homeassistant.components.fan
Source: components/fan/__init__.py:295
integration: Fan (documentation, issues)
First occurred: 00:25:46 (4 occurrences)
Last logged: 00:26:13

    Entity None (<class 'custom_components.bayernluefter.fan.BayernluefterFan'>) does not set FanEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/mampfes/ha_bayernluefter/issues
    Entity None (<class 'custom_components.bayernluefter.fan.BayernluefterFan'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/mampfes/ha_bayernluefter/issues
```

What other kind of information can I submit to help with this problem?

**Comment by MaxiKingXXL** [comment]
Same issue for me:
Logger: homeassistant.components.fan
Quelle: components/fan/__init__.py:295
Integration: Lüfter (Dokumentation, Probleme)
Erstmals aufgetreten: 21:00:11 (6 Vorkommnisse)
Zuletzt protokolliert: 21:00:15

Entity None (<class 'custom_components.bayernluefter.fan.BayernluefterFan'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/mampfes/ha_bayernluefter/issues
