### ISSUE TITLE
Update not possible

### ISSUE THREAD

**Issue by Uli1900** [mampfes/ha_bayernluefter#2]
Hallo, seit der Installation in HA kommt der Updatedialog. Wenn ich auf installieren klicke, dann tut sich nix.

Was kann ich tun um den Fehler zu beheben?

![image](https://github.com/mampfes/ha_bayernluefter/assets/98254065/6d65a135-8a70-4f3f-9d7d-582545c8e0a6)

Danke und vg

**Comment by mampfes** [comment]
Ich vermute sie haben eine andere (ältere) HW Version, welche eine andere Firmware benötigt. Da ich selber nur ein Gerät besitze, ist mir dieser Unterschied noch nie begegnet.

Welche Version wird bei ihnen in der Geräteinformation angezeigt?
![image](https://github.com/mampfes/ha_bayernluefter/assets/375950/9c0243ce-a82d-4e2c-9ee8-7cad55f772b7)

**Comment by Uli1900** [comment]
Das ist meine Firmware:

![image](https://github.com/mampfes/ha_bayernluefter/assets/98254065/d9fea1dd-dd9a-416c-985d-de571538e0e6)

**Comment by mampfes** [comment]
Das Problem sollte in Version 1.2.2 gefixt sein. Können sie bitte mit dieser Version ausprobieren ob das Update bei ihnen richtig angezeigt wird? Ich habe leider kein passendes Gerät zum Testen.

**Comment by Uli1900** [comment]
Hab 2 Geräte, HA zeigt immer an, das ein update vorhanden ist, ein klick auf installieren bringt nichts:



Das ist das ältere (hat ein neues W-Lan Modul vor 2 Wochen vom Hersteller bekommen): 

![image](https://github.com/mampfes/ha_bayernluefter/assets/98254065/97858b46-75a3-4755-ac39-87c916c76960)
![image](https://github.com/mampfes/ha_bayernluefter/assets/98254065/17d02659-d135-43f6-96fd-e3b00ed27334)


Das ist mein 2. Gerät (gleich wie 1. Gerät):

![image](https://github.com/mampfes/ha_bayernluefter/assets/98254065/cb0e4272-46c5-4227-a54d-7b065dbf4dc4)
![image](https://github.com/mampfes/ha_bayernluefter/assets/98254065/0a7d515b-70e0-4bfa-98a4-e83c5b18db7b)

**Comment by mampfes** [comment]
Ok, danke. Haben die schon die neue Version 1.2.2 ausprobiert? Die sollte keine Updates-Aufforderung mehr anzeigen.

**Comment by Uli1900** [comment]
Hallo, was meinen Sie mit "ausprobiert"???

**Comment by mampfes** [comment]
Können sie bitte die neue Version 1.2.2 installieren (via HACS) und mir mitteilen ob damit immer noch die fehlerhafte Update Benachrichtigung angezeigt wird?

**Comment by Uli1900** [comment]
Hallo, danke für den Hinweis und die Aktualisierung der Software!

Ich hab es upgedatet, jetzt ist die FW aktuell:
 
![image](https://github.com/mampfes/ha_bayernluefter/assets/98254065/3b1d3497-8e87-4644-857f-fdeb14e2f0fe)
