### ISSUE TITLE
Error requesting bayernluefter data: 400

### ISSUE THREAD

**Issue by ubarni** [mampfes/ha_bayernluefter#3]
Hi,

i can see the correct data in Home Assistant but i often see the following error in my logs:
`2024-01-04 17:34:46.574 ERROR (MainThread) [custom_components.bayernluefter] Error requesting bayernluefter data: 400, message="Data after Connection: close:\n\n  b'0'\n     ^", url=URL('http://192.168.178.50/?export=1')`
I uploaded the correct export.txt and rebooted Bayernlüfer and Home Assistant.

Regards...
Uwe

**Comment by mampfes** [comment]
Looks like a communication problem, either with your WLAN, your Home Assistant Server or your Bayernlüfter device.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400

**Comment by ubarni** [comment]
Thanks for clarifying. Normally all my smart home devices works fine so far.
So if no one else complains it seems to be an issue with my wifi.

**Comment by mampfes** [comment]
Please let me know if you see this issue very often. Maybe we can find a workaround.
