### ISSUE TITLE
Metriken 

### ISSUE THREAD

**Issue by hlinden** [mampfes/ha_bayernluefter#6]
![Bildschirmfoto vom 2024-03-15 13-26-00](https://github.com/mampfes/ha_bayernluefter/assets/4718458/be82607d-6e63-4d36-9dd8-6e5a7323a1bc)
![Bildschirmfoto vom 2024-03-15 13-25-47](https://github.com/mampfes/ha_bayernluefter/assets/4718458/045a1ffd-4100-4540-98d8-17510c2583d7)

Intuitiv würde ich erwarten, dass "In" die Ansaugtemperatur innen und "Out" die Ausgabetemperatur unten am Gehäuse liefert. Will man da genauer drauf schauen?

**Comment by hlinden** [comment]
![Bildschirmfoto vom 2024-03-15 13-26-00](https://github.com/mampfes/ha_bayernluefter/assets/4718458/be82607d-6e63-4d36-9dd8-6e5a7323a1bc)
![Bildschirmfoto vom 2024-03-15 13-25-47](https://github.com/mampfes/ha_bayernluefter/assets/4718458/045a1ffd-4100-4540-98d8-17510c2583d7)

Intuitiv würde ich erwarten, dass "In" die Ansaugtemperatur innen und "Out" die Ausgabetemperatur unten am Gehäuse liefert. Will man da genauer drauf schauen?

**Comment by mampfes** [comment]
Die Namen sind von Bayernluft übernommen. Temp_Fresh ist Aussentemperatur, Temp_In die Temperatur der aufgewärmten Aussenluft, Temp_Out ist die Temperatur der ausströmenden Luft.

**Comment by hlinden** [comment]
Okay, ich hatte immer gedacht, der Wert in der GUI oben links wäre die aus dem Raum angesaugte Luft. Ist auch nicht so wichtig, ich hab die Werte in meinen Grafana-Dashboards jetzt einfach getauscht, "Temp-Out" ist da jetzt halt einfach die Raumtemperatur.

Mach das Issue zu, wenn du da nix zu ändern siehst, alles jut.

**Comment by mampfes** [comment]
> der Wert in der GUI oben links wäre die aus dem Raum angesaugte Luft
Ja, das stimmt. Und das nennt Bayernluft TempOut. Also die nach draussen strömende Luft vor dem Wärmetauscher. Nach dem Wärmetauscher wird die nach draussen strömende Luft nicht mehr gemessen. Im Gegensatz zur in den Raum einströmenden Luft.

Ich hoffe damit sämtliche Klarheiten beseitigt zu haben :-)
