### ISSUE TITLE
KeyError: '_MaxMode'

### ISSUE THREAD

**Issue by jrodan** [mampfes/ha_bayernluefter#9]
Hey, 
I am running the plugin since a few days in a containerized HA runtime.
I am not sure if that error is new, but at least right now this is spamming in my logs.

HA Core 2024.8.1

`homeassistant  | 2024-08-12 23:38:41.662 ERROR (MainThread) [homeassistant.components.shelly] Error connecting to Shelly device Shelly, error: DeviceConnectionError(DeviceConnectionError(ClientConnectorError(ConnectionKey(host='192.168.178.77', port=80, is_ssl=False, ssl=True, proxy=None, proxy_auth=None, proxy_headers_hash=-1379029246200924891), OSError(113, "Connect call failed ('192.168.178.77', 80)"))))
homeassistant  | 2024-08-12 23:38:42.628 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
homeassistant  | Traceback (most recent call last):
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _handle_refresh_interval
homeassistant  |     await self._async_refresh(log_failures=True, scheduled=True)
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 453, in _async_refresh
homeassistant  |     self.async_update_listeners()
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
homeassistant  |     update_callback()
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 533, in _handle_coordinator_update
homeassistant  |     self.async_write_ha_state()
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state
homeassistant  |     self._async_write_ha_state()
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
homeassistant  |     self.__async_calculate_state()
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1069, in __async_calculate_state
homeassistant  |     if state_attributes := self.state_attributes:
homeassistant  |                            ^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 255, in __getattribute__
homeassistant  |     return super().__getattribute__(__name)
homeassistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 526, in state_attributes
homeassistant  |     data[ATTR_PRESET_MODE] = self.preset_mode
homeassistant  |                              ^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 255, in __getattribute__
homeassistant  |     return super().__getattribute__(__name)
homeassistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/config/custom_components/bayernluefter/fan.py", line 88, in preset_mode
homeassistant  |     if self._device.raw_converted()["_MaxMode"]:
homeassistant  |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
homeassistant  | KeyError: '_MaxMode'`

`homeassistant  | 2024-08-12 23:45:42.694 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
homeassistant  | Traceback (most recent call last):
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _handle_refresh_interval
homeassistant  |     await self._async_refresh(log_failures=True, scheduled=True)
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 453, in _async_refresh
homeassistant  |     self.async_update_listeners()
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
homeassistant  |     update_callback()
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 533, in _handle_coordinator_update
homeassistant  |     self.async_write_ha_state()
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state
homeassistant  |     self._async_write_ha_state()
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
homeassistant  |     self.__async_calculate_state()
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1069, in __async_calculate_state
homeassistant  |     if state_attributes := self.state_attributes:
homeassistant  |                            ^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 255, in __getattribute__
homeassistant  |     return super().__getattribute__(__name)
homeassistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 526, in state_attributes
homeassistant  |     data[ATTR_PRESET_MODE] = self.preset_mode
homeassistant  |                              ^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 255, in __getattribute__
homeassistant  |     return super().__getattribute__(__name)
homeassistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/config/custom_components/bayernluefter/fan.py", line 88, in preset_mode
homeassistant  |     if self._device.raw_converted()["_MaxMode"]:
homeassistant  |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
homeassistant  | KeyError: '_MaxMode'`

Any idea why this error occurs and how to fix it?
Thanks!

**Comment by mampfes** [comment]
Did you follow the instructions regarding template file?
https://github.com/mampfes/ha_bayernluefter?tab=readme-ov-file#template-file

**Comment by git4-me** [comment]
I had the exact same problem. Indeed, updating the export.txt on the Bayernlüfter solved the problem for me.

I'd still consider this a bug as the integration should work without any errors on factory standard devices without a modified export.txt file.

**Comment by mampfes** [comment]
Please check latest version 2.0.0

**Comment by git4-me** [comment]
Thanks for the fix. I'm still running the modified export.txt file. Do you want me to revert back to the original export settings and try with version 2.0.0?

**Comment by mampfes** [comment]
Oh, yes, this would be an interesting test. Thanks.
